workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Park4Me Push Notification
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.park4me.pushNotification
      vars:
        BUNDLE_ID: "com.park4me.pushNotification"
        XCODE_WORKSPACE: "ParkMe.xcworkspace"
        XCODE_SCHEME: "Park4Me"
        APP_STORE_APPLE_ID: 6738696238
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods Dependencies
        script: |
          pod install --repo-update --verbose
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --configuration "Release"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - vincentpsmith88@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups: 
          - QA Testers
          - Internal Team
        submit_to_app_store: false
